version: '3'
services:
  quarkus-service:
    container_name: javaexample
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm # maybe ".native" ?
    image: java/javaexample:jvm
#    mem_limit: 128m
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresdb:5432/quarkusdb
    ports:
      - "8080:8080"
    depends_on:
      - db
